### ISSUE TITLE
should try to reuse downloaded apk

### ISSUE THREAD

**Issue by cani1see** [mikehardy/react-native-update-apk#18] opened 2019-08-12 07:28 UTC
please try to reuse downloaded apk if the user already download once, no reason to download again.

**Comment by mikehardy** [comment] 2019-08-12 13:21
I'm going to resolve this as a duplicate of #6 as it depends on that and is mentioned there (not just re-use, but incremental / continuation of download)

But in general I want to say, I completely agree!

If you want to propose a PR that adds a checksum to the descriptor per #6 and can verify the file after download (or if it exists already) I'd merge it in immediately

**Closed** 2019-08-12 13:22 UTC
