### ISSUE TITLE
java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.xxx.xxxx

### ISSUE THREAD

**Issue by fairyland0926** [mikehardy/react-native-update-apk#40] opened 2021-03-14 01:15 UTC
![Screenshot_1](https://user-images.githubusercontent.com/72979420/111054220-c3dfaa80-841f-11eb-9bd0-1687647759b3.png)

**Comment by mikehardy** [comment] 2021-03-14 14:46
Hi there! I have seen some odd behavior recently in my app that might be explained by this but since I just use to update dev versions of my app I haven't paid much attention.

1) PRs happily merged! If you need this fixed, I will likely need to get a PR from the community (that is, you) to fix it as I don't have time to personally troubleshoot it, but I'm happy to collaborate on a PR if you post one, then merge it and release

2) You have provided no information necessary to troubleshoot. You could be on Android 4.1, react-native 0.58 and the first version of this module. So I couldn't help anyway :sweat_smile: 

3) Please reproduce with the example app as a basis for a PR to fix - that way we have (mostly? I haven't refreshed the example in a while) up to date code that we share as a basis for collaboration

**Comment by fairyland0926** [comment] 2021-06-05 14:12
Thank you good working. :)

**Closed** 2021-06-05 14:12 UTC
Labels: question, waiting for feedback
